using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassGenerator.Classes
{
	/// <summary>
	/// Field Property
	/// </summary>
	public enum EnumFieldProperty
	{
		TABLE_CATALOG,
		TABLE_SCHEMA,
		TABLE_NAME,
		COLUMN_NAME,
		ORDINAL_POSITION,
		COLUMN_DEFAULT,
		IS_NULLABLE,
		DATA_TYPE,
		CHARACTER_MAXIMUM_LENGTH,
		CHARACTER_OCTET_LENGTH,
		NUMERIC_PRECISION,
		NUMERIC_PRECISION_RADIX,
		NUMERIC_SCALE,
		DATETIME_PRECISION,
		CHARACTER_SET_CATALOG,
		CHARACTER_SET_SCHEMA,
		CHARACTER_SET_NAME,
		COLLATION_CATALOG,
		COLLATION_SCHEMA,
		COLLATION_NAME,
		DOMAIN_CATALOG,
		DOMAIN_SCHEMA,
		DOMAIN_NAME,
		CONSTRAINT_CATALOG,
		CONSTRAINT_SCHEMA,
		FK_CONSTRAINT_NAME,
		FK_TABLE_NAME,
		FK_COLUMN_NAME,
		FK_ORDINAL_POSITION,
		REFERENCED_CONSTRAINT_NAME,
		REFERENCED_TABLE_NAME,
		REFERENCED_COLUMN_NAME,
		REFERENCED_ORDINAL_POSITION,
		UPDATE_RULE,
		DELETE_RULE,
		CSharpDataType
	}
}
